name: Whitetails_werewolf
version: '1.0-SNAPSHOT'
main: net.cherryleaves.whitetails_werewolf.Whitetails_werewolf
api-version: '1.21'
authors: [ 桜葉 尊宏 ]
description: This is a test mod.
website: https://mc.cherry-leaves.net
